### ISSUE TITLE
DNS A record update

### ISSUE THREAD

**Issue by linc01n** [codeaholicshk/codeaholicshk.github.io#2]
The existing DNS record on codeaholics.hk is still pointing to 204.232.175.78

Before 2 Feb, 2015 we need to update the A record to point to 

**192.30.252.153**
**192.30.252.154**

For more info: 
https://github.com/blog/1917-github-pages-legacy-ip-deprecation

> We wanted to follow-up on the email we sent back you in November about custom domains on GitHub Pages sites. To help us improve how we serve GitHub Pages, we’re deprecating our old GitHub Pages IP addresses.
> 
> The following domains owned by your account will be affected by this deprecation:
> 
> codeaholics.hk (hosted at https://github.com/codeaholicshk/codeaholicshk.github.io)

**Comment by matthewrudy** [comment]
Cheers, Lincoln.
Steve is sorting this out,
And trying to hand the domain over to Eddie.

**Comment by linc01n** [comment]
:+1:
